<?php
/**
 * Template Name: Sitemap
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

// Remove default loop.
remove_action( 'genesis_before_loop', 'genesis_do_breadcrumbs' );
remove_action( 'genesis_loop', 'genesis_do_loop' );
add_action('genesis_loop','sitemap_function');

function sitemap_function() {

	genesis_markup( array(
		'open' => '<article class="entry">',
		'context' => 'sitemap',
	) );

		printf( '<h1 class="entry-title">%s</h1>', apply_filters( 'genesis_sitemap', __( 'Sitemap', 'genesis' ) ) );
		echo '<div class="entry-content">';
				wp_list_pages(array('exclude'=> '2685, 1340, 1328'));
		echo '</div>';

	genesis_markup( array(
		'close' => '</article>',
		'context' => 'sitemap',
	) );

}

genesis();
